--This file should contain the SQL to create a new TYPE called grocery and a new TABLE called shopping_list
--The table will contain 6 columns and you will need to decide which SQL data types to use for each column.

--The grocery TYPE should be an ENUM that can be one of the following possible values:
--Main, snack, lunch, breakfast

--The shopping_list table should have the following 6 columns:
--primary key column id
--name column
--price column that should support 2 decimal places
--a date_added column that should default to now()
--a checked column that should be a BOOLEAN with default false
--a category column, use the grocery type you created for this column

DROP TYPE IF EXISTS grocery_type;

CREATE TYPE grocery_type as ENUM (
  'Main',
  'Snack',
  'Lunch',
  'Breakfast'
);

CREATE TABLE IF NOT EXISTS shopping_list (
  item_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  price decimal(12,2) NOT NULL,
  date_added TIMESTAMP DEFAULT now() NOT NULL,
  checked BOOLEAN default false,
  category grocery_type NOT NULL
);